// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJ6UJ6T9aGdGPjrLaR2EKCsHRxXWv2MQ',
    appId: '1:597482293472:web:58c49de21a5038ee9d2885',
    messagingSenderId: '597482293472',
    projectId: 'localbazzar-82025',
    authDomain: 'localbazzar-82025.firebaseapp.com',
    storageBucket: 'localbazzar-82025.firebasestorage.app',
    measurementId: 'G-FV8639JWRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnSiLaBD_yETiQUQQZClrhcdUXYLoJy2w',
    appId: '1:597482293472:android:e1cd044e006eb3179d2885',
    messagingSenderId: '597482293472',
    projectId: 'localbazzar-82025',
    storageBucket: 'localbazzar-82025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6e47QHuY1FAe1733a5gj-KW6tireRM8U',
    appId: '1:597482293472:ios:8b6524aa77b6e21f9d2885',
    messagingSenderId: '597482293472',
    projectId: 'localbazzar-82025',
    storageBucket: 'localbazzar-82025.firebasestorage.app',
    iosBundleId: 'com.example.localbazzar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6e47QHuY1FAe1733a5gj-KW6tireRM8U',
    appId: '1:597482293472:ios:8b6524aa77b6e21f9d2885',
    messagingSenderId: '597482293472',
    projectId: 'localbazzar-82025',
    storageBucket: 'localbazzar-82025.firebasestorage.app',
    iosBundleId: 'com.example.localbazzar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUJ6UJ6T9aGdGPjrLaR2EKCsHRxXWv2MQ',
    appId: '1:597482293472:web:3a61e7bf69d801539d2885',
    messagingSenderId: '597482293472',
    projectId: 'localbazzar-82025',
    authDomain: 'localbazzar-82025.firebaseapp.com',
    storageBucket: 'localbazzar-82025.firebasestorage.app',
    measurementId: 'G-H2PVLF33MQ',
  );
}
